<h2 style="color:Red; font-weight:bold;">Basic Pandas Practice</h2>

__1️⃣ Create DataFrame__

Create a DataFrame with columns:

    Name
    Age
    Salary
    Department

Add at least 5 employees.

Then:

    Show first 3 rows
    Show last 2 rows
    Show column names

In [3]:
import pandas as pd

In [4]:
data = {
    "Name":["Pushpkar Roy","Anurag Karn","Piysuh Rathor","Gayak Jan","Anu Thakur","Atirek Sahil"],
    "Age":[22,21,20,23,21,23],
    "Salary":[55000,35000,50000,41000,20000,25000],
    "Department":["Data Analyst","Accountant", "Cloud AI","Cloud AI", "BDE","BDE"]
}

In [5]:
employes = pd.DataFrame(data)
employes

            Name  Age  Salary    Department
0   Pushpkar Roy   22   55000  Data Analyst
1    Anurag Karn   21   35000    Accountant
2  Piysuh Rathor   20   50000      Cloud AI
3      Gayak Jan   23   41000      Cloud AI
4     Anu Thakur   21   20000           BDE
5   Atirek Sahil   23   25000           BDE

1. Show first 3 rows
2. Show last 2 rows
3. Show column names

In [6]:
# Show first 3 line 
employes.head(3)

            Name  Age  Salary    Department
0   Pushpkar Roy   22   55000  Data Analyst
1    Anurag Karn   21   35000    Accountant
2  Piysuh Rathor   20   50000      Cloud AI

In [7]:
# Show last 2 Rows 
employes.tail(2)

           Name  Age  Salary Department
4    Anu Thakur   21   20000        BDE
5  Atirek Sahil   23   25000        BDE

In [8]:
# Show column names 
employes.columns

Index(['Name', 'Age', 'Salary', 'Department'], dtype='object')

2️⃣ Filtering Practice

From employee DataFrame:

    Show employees with Salary > 50000
    Show employees from "Cloud AI" department
    Show employees with Age between 25 and 35

In [9]:
# Show employees with Salary > 50000
employes[employes["Salary"] > 50000]

           Name  Age  Salary    Department
0  Pushpkar Roy   22   55000  Data Analyst

In [10]:
# Show employees from "Cloud AI" department 
employes[employes["Department"] == "Cloud AI"]

            Name  Age  Salary Department
2  Piysuh Rathor   20   50000   Cloud AI
3      Gayak Jan   23   41000   Cloud AI

In [11]:
# Show employees from "Cloud AI " Department   # Other way to solve this question 
employes.query("Department == 'Cloud AI'")

            Name  Age  Salary Department
2  Piysuh Rathor   20   50000   Cloud AI
3      Gayak Jan   23   41000   Cloud AI

In [12]:
# Show employees with Age between 22 and 25
employes[(employes["Age"] >= 22) & (employes["Age"] <= 25)]

           Name  Age  Salary    Department
0  Pushpkar Roy   22   55000  Data Analyst
3     Gayak Jan   23   41000      Cloud AI
5  Atirek Sahil   23   25000           BDE

In [13]:
# Show employees with Age between 22 and 25    # Other way using query like SQL 
employes.query("Age >= 22 and Age <= 25")

           Name  Age  Salary    Department
0  Pushpkar Roy   22   55000  Data Analyst
3     Gayak Jan   23   41000      Cloud AI
5  Atirek Sahil   23   25000           BDE

## 🟡 Level 2 – GroupBy Practice (Very Important 🔥)
__6️⃣ Department Analysis__

Using employee DataFrame:

    Find average salary per department
    Find highest salary per department
    Count employees per department

In [14]:
# Find average Salary per department 
employes.groupby("Department")["Salary"].mean()

Department
Accountant      35000.0
BDE             22500.0
Cloud AI        45500.0
Data Analyst    55000.0
Name: Salary, dtype: float64

In [15]:
# Find highest Salary per department 
employes.groupby("Department")["Salary"].max()

Department
Accountant      35000
BDE             25000
Cloud AI        50000
Data Analyst    55000
Name: Salary, dtype: int64

In [16]:
# Find highest Salary per department    # Other eay 
employes.loc[employes.groupby("Department")["Salary"].idxmax()]

            Name  Age  Salary    Department
1    Anurag Karn   21   35000    Accountant
5   Atirek Sahil   23   25000           BDE
2  Piysuh Rathor   20   50000      Cloud AI
0   Pushpkar Roy   22   55000  Data Analyst

In [17]:
# Count employees as per the department 
employes.groupby("Department")["Department"].count()

Department
Accountant      1
BDE             2
Cloud AI        2
Data Analyst    1
Name: Department, dtype: int64

7️⃣ Real-World: Sales Dataset

Create DataFrame:

| OrderID | Product | Quantity | Price |

Then:

    Create new column: Total = Quantity * Price
    Find total revenue
    Find product with highest total sales
    Find average order value

In [18]:
data = {
    "OrderID":[101,102,103,104,105,106,107,108,109],
    "Product":["Apple","Banana","Mango","Apple","Apple","Banana","Orange","Mango","Mango"],
    "Quantity":[10,12,20,5,12,12,7,12,15],
    "Price":[20,5,25,20,20,5,15,25,25]
}

In [19]:
shop = pd.DataFrame(data)

In [20]:
shop

   OrderID Product  Quantity  Price
0      101   Apple        10     20
1      102  Banana        12      5
2      103   Mango        20     25
3      104   Apple         5     20
4      105   Apple        12     20
5      106  Banana        12      5
6      107  Orange         7     15
7      108   Mango        12     25
8      109   Mango        15     25

In [21]:
# Create new column: Total Revenue = quantity * price 
shop["Total Revenue"] = shop["Quantity"] * shop["Price"]
shop

   OrderID Product  Quantity  Price  Total Revenue
0      101   Apple        10     20            200
1      102  Banana        12      5             60
2      103   Mango        20     25            500
3      104   Apple         5     20            100
4      105   Apple        12     20            240
5      106  Banana        12      5             60
6      107  Orange         7     15            105
7      108   Mango        12     25            300
8      109   Mango        15     25            375

In [22]:
# Find product with the highest total sales 
shop.groupby("Product")["Total Revenue"].sum()

Product
Apple      540
Banana     120
Mango     1175
Orange     105
Name: Total Revenue, dtype: int64

In [23]:
# Find avg order value 
total_revenue = shop["Total Revenue"].sum()           # Total Revenue / Total order = AOV (Avg order value)
total_order = shop["OrderID"].count()

aov = total_revenue / total_order
aov

np.float64(215.55555555555554)

In [24]:
# Find avg order value               # Single step method 
shop["Total Revenue"].mean()

np.float64(215.55555555555554)

8️⃣ Value Counts Practice

Create a column "City"

    Count how many employees from each city
    Find most common city

In [25]:
employes

            Name  Age  Salary    Department
0   Pushpkar Roy   22   55000  Data Analyst
1    Anurag Karn   21   35000    Accountant
2  Piysuh Rathor   20   50000      Cloud AI
3      Gayak Jan   23   41000      Cloud AI
4     Anu Thakur   21   20000           BDE
5   Atirek Sahil   23   25000           BDE

In [26]:
employes["City"] = ["Jabalpur","Bhopal","Bhopal","Indore","Bhopal","Indore"]
employes

            Name  Age  Salary    Department      City
0   Pushpkar Roy   22   55000  Data Analyst  Jabalpur
1    Anurag Karn   21   35000    Accountant    Bhopal
2  Piysuh Rathor   20   50000      Cloud AI    Bhopal
3      Gayak Jan   23   41000      Cloud AI    Indore
4     Anu Thakur   21   20000           BDE    Bhopal
5   Atirek Sahil   23   25000           BDE    Indore

In [27]:
employes.groupby("Name")["City"].count()

Name
Anu Thakur       1
Anurag Karn      1
Atirek Sahil     1
Gayak Jan        1
Piysuh Rathor    1
Pushpkar Roy     1
Name: City, dtype: int64

In [28]:
# Count how many employees from each city 
employes.groupby("City").value_counts()

City      Name           Age  Salary  Department
Bhopal    Anu Thakur     21   20000   BDE             1
          Anurag Karn    21   35000   Accountant      1
          Piysuh Rathor  20   50000   Cloud AI        1
Indore    Atirek Sahil   23   25000   BDE             1
          Gayak Jan      23   41000   Cloud AI        1
Jabalpur  Pushpkar Roy   22   55000   Data Analyst    1
Name: count, dtype: int64

In [29]:
# Find most common city 
employes.groupby("City").size()

City
Bhopal      3
Indore      2
Jabalpur    1
dtype: int64

In [30]:
# Find most common city         # 2nd method
employes.groupby("City")["City"].count()

City
Bhopal      3
Indore      2
Jabalpur    1
Name: City, dtype: int64

## 🟠 Level 3 – Slightly Logical
__9️⃣ Remove Duplicates__

Create DataFrame with duplicate rows.

    Remove duplicates
    Reset index

In [31]:
import pandas as pd
import numpy as np  

data = {
    'Employee_ID': [101, 102, 103, 101, 104, 105, 105],
    'Name': ['Alice', 'Bob', 'Charlie', 'Alice', 'David', 'Eve', 'Eve'],
    'Department': ['HR', 'IT', 'Marketing', 'HR', np.nan, 'Sales', 'Sales'],
    'Salary': [50000, 60000, np.nan, 50000, 55000, 70000, 70000]
}

In [32]:
comp = pd.DataFrame(data)
comp

   Employee_ID     Name Department   Salary
0          101    Alice         HR  50000.0
1          102      Bob         IT  60000.0
2          103  Charlie  Marketing      NaN
3          101    Alice         HR  50000.0
4          104    David        NaN  55000.0
5          105      Eve      Sales  70000.0
6          105      Eve      Sales  70000.0

In [33]:
# Find and remove duplicates 

comp.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
dtype: bool

In [34]:
comp[comp.duplicated()]

   Employee_ID   Name Department   Salary
3          101  Alice         HR  50000.0
6          105    Eve      Sales  70000.0

In [35]:
# Remove Duplicates 
comp = comp.drop_duplicates()

In [36]:
comp

   Employee_ID     Name Department   Salary
0          101    Alice         HR  50000.0
1          102      Bob         IT  60000.0
2          103  Charlie  Marketing      NaN
4          104    David        NaN  55000.0
5          105      Eve      Sales  70000.0

In [37]:
# Reset Index 
comp.reset_index()
comp

   Employee_ID     Name Department   Salary
0          101    Alice         HR  50000.0
1          102      Bob         IT  60000.0
2          103  Charlie  Marketing      NaN
4          104    David        NaN  55000.0
5          105      Eve      Sales  70000.0

In [38]:
comp.isnull().sum()

Employee_ID    0
Name           0
Department     1
Salary         1
dtype: int64

In [39]:
comp.fillna("I don't know")

   Employee_ID     Name    Department        Salary
0          101    Alice            HR       50000.0
1          102      Bob            IT       60000.0
2          103  Charlie     Marketing  I don't know
4          104    David  I don't know       55000.0
5          105      Eve         Sales       70000.0

In [40]:
# How to fill salary missing value 
comp["Salary"].fillna(comp["Salary"].mean(), inplace= True)

C:\Users\pushp\AppData\Local\Temp\ipykernel_13284\2914520199.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  comp["Salary"].fillna(comp["Salary"].mean(), inplace= True)
C:\Users\pushp\AppData\Local\Temp\ipykernel_13284\2914520199.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  comp["Salary"].fillna(comp["Salary"].mean(), inplace= True)

In [41]:
comp

   Employee_ID     Name Department   Salary
0          101    Alice         HR  50000.0
1          102      Bob         IT  60000.0
2          103  Charlie  Marketing  58750.0
4          104    David        NaN  55000.0
5          105      Eve      Sales  70000.0

In [42]:
# Fill Department missing value 
comp["Department"].fillna("IT", inplace= True)

C:\Users\pushp\AppData\Local\Temp\ipykernel_13284\1584783160.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  comp["Department"].fillna("IT", inplace= True)
C:\Users\pushp\AppData\Local\Temp\ipykernel_13284\1584783160.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  comp["Department"].fillna("IT", inplace= True)

In [43]:
comp

   Employee_ID     Name Department   Salary
0          101    Alice         HR  50000.0
1          102      Bob         IT  60000.0
2          103  Charlie  Marketing  58750.0
4          104    David         IT  55000.0
5          105      Eve      Sales  70000.0

🔟 Apply Function

Create a function:

    If Salary > 70000 → "High"
    If 40000–70000 → "Medium"
    Else → "Low"

In [44]:
salary = comp["Salary"]
salary

0    50000.0
1    60000.0
2    58750.0
4    55000.0
5    70000.0
Name: Salary, dtype: float64

In [45]:
salary_slab = []
for i in salary:
    if i >= 70000:
        salary_slab.append("High")
    elif i >= 52000 and i < 70000:
        salary_slab.append("Medium")
    else:
        salary_slab.append("Low")
print(salary_slab)

['Low', 'Medium', 'Medium', 'Medium', 'High']

In [46]:
comp["Salary_Level"] = salary_slab

C:\Users\pushp\AppData\Local\Temp\ipykernel_13284\535450160.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  comp["Salary_Level"] = salary_slab

In [47]:
comp

   Employee_ID     Name Department   Salary Salary_Level
0          101    Alice         HR  50000.0          Low
1          102      Bob         IT  60000.0       Medium
2          103  Charlie  Marketing  58750.0       Medium
4          104    David         IT  55000.0       Medium
5          105      Eve      Sales  70000.0         High