In [1]:
import numpy as np

<h2 style="color:darkorange; font-weight:bold;">Pyhon and Pandas Exam</h2>

<h2 style="color:Green; font-weight:bold;">Section A (1 Marks Questions.)</h2>

__Q1. Create a list of numbers from 1 to 10 using Python.__

In [2]:
# Using For loop function 
for i in range(1,11,1):
    print(i)

1
2
3
4
5
6
7
8
9
10

In [3]:
# Usining While loop question.
i = 1
while 10 >= i:
    print(i)
    i += 1

1
2
3
4
5
6
7
8
9
10

__Q2. Write a Python expression to get square of each number in a list using list comprehension.__

Example list:

    nums = [2,4,6]

In [4]:
nums = [2,4,6]
squre = []

for i in nums:
    j = i ** 2
    squre.append(j)
print(squre)

[4, 16, 36]

__Q3. Write a command to import pandas.__

In [5]:
import pandas as pd

__Q4. Create a Pandas Series from the list:__

    [10,20,30,40]

In [6]:
my_list = [10,20,30,40]
my_series = pd.Series(my_list)
my_series

0    10
1    20
2    30
3    40
dtype: int64

__Q5. Write code to display first 5 rows of a dataframe df__

In [7]:
df = my_series

In [8]:
df.head()

0    10
1    20
2    30
3    40
dtype: int64

__Q6. Write code to check missing values in dataframe__

In [9]:
df.isnull()

0    False
1    False
2    False
3    False
dtype: bool

In [10]:
# For the large dataset 
df.isnull().sum()

np.int64(0)

__Q7. Write code to remove rows with missing values__

In [ ]:
df = df[df["Row_Name"].notna()]

__Q8. Write code to sort dataframe by column "price"__

In [ ]:
df["Column_Name"]

__Q9. Write code to find unique values in column "city"__

In [ ]:
df["City"].unique()

__Q10. Write code to calculate mean of column "salary"__

In [ ]:
df["Salary"].mean()

__Q11. Write code to group data by "department"__

In [ ]:
df.groupby("Department")["Column_name"].sum()

__Q12. Write code to rename column "old_name" to "new_name"__

In [ ]:
df = df.rename(columns = {"Old_Name","New_Name"})

__Q13. Write code to convert column "date" to datetime__

In [ ]:
df = pd.to_datetime(df["Date"])

__Q14. Write code to count occurrences of each product__

In [ ]:
count_occurrences = df["Column_name"].value_counts()

__Q15. Write code to save dataframe to CSV file__

In [ ]:
df.to_csv("File Path")

<h2 style="color:Green; font-weight:bold;">Section B (2 Marks Questions.)</h2>

__Q16. Write a Python function that returns sum of two numbers.__

In [ ]:
first_no = int(input("Enter your first value :- "))
second_no = int(input("Enter your 2nd value:- "))

final_result = first_no + second_no
final_result

30

__Q17. Write a Python program to find maximum number in a list.__

In [ ]:
list = [10,20,40,50,20,55,75,44,65,1]

list.sort()

for i in range(len(list)-1,-1,-1):
    k = list[i]
    print("The maximum Number in this list is ",k)
    break

The maximum Number in this list is  75

__Q18. Create a dictionary of 3 students and their marks.__

    Then print the marks of one specific student.

In [ ]:
students = {
    "Pranshu":55,
    "Harsh":62,
    "Karan":45
}

print("Total Marks of Pranshu is:-", students["Pranshu"])
print("Total Marks of Harsh is:-",students["Harsh"])
print("Total Marks of Karan is:-",students["Karan"])

Total Marks of Pranshu is:- 55
Total Marks of Harsh is:- 62
Total Marks of Karan is:- 45

__Q19. Python Dictionary (2 Marks)__

Create a dictionary containing 3 products and their prices.

    Example structure:

    products = {
        "Laptop": 60000,
        "Mouse": 500,
        "Keyboard": 1500
    }

Then write code to:

    Print the price of "Laptop"
    Add a new product "Monitor" with price 12000

In [ ]:
products = {
    "Laptop":60000,
    "Mouse":500,
    "Keyboard":1500
}

products 
print("the price of the product Laptop is:-", products["Laptop"])

products["Moniter"] = 12000
print(products)

the price of the product Laptop is:- 60000
{'Laptop': 60000, 'Mouse': 500, 'Keyboard': 1500, 'Moniter': 12000}

__Q20. Write Pandas code to filter rows where salary > 50000__

In [ ]:
df[df["Salary"]> 50000]

<h2 style="color:Green; font-weight:bold;">Section C (3 Marks Questions.)</h2>

__Q21. Create a DataFrame with columns:__

    Name
    Age
    Salary

        Add at least 5 rows of data.
        Then display employees whose salary > 40000.

In [ ]:
data = {
    "Name":["Monty","Anurag","Piyush","Khshi","Gyayak","Yash"],
    "Age":[22,20,19,22,23,21],
    "Salary":[55000,40000,60000,30000,35000,42000]
}

friend = pd.DataFrame(data)
friend

     Name  Age  Salary
0   Monty   22   55000
1  Anurag   20   40000
2  Piyush   19   60000
3   Khshi   22   30000
4  Gyayak   23   35000
5    Yash   21   42000

In [ ]:
friend[friend["Salary"] >= 40000]

     Name  Age  Salary
0   Monty   22   55000
1  Anurag   20   40000
2  Piyush   19   60000
5    Yash   21   42000

__Q22. Write Python code to count frequency of each element in a list.__

Example:    
    [1,2,2,3,3,3]

In [ ]:
list = [1,2,2,2,3,3,3,4]
new_list = []
dec = {}
counting = 1

for i in list:
    if i not in new_list:
        dec[i] = 1
        new_list.append(i)
    elif i in new_list:
        counting = counting + 1
        dec[i] = counting

print(dec)

{1: 1, 2: 3, 3: 5, 4: 1}

In [ ]:
# Other way give some help from Google 
my_list = [1, 2, 2, 2, 3, 3, 3, 4]
dec = {}

for i in my_list:
    if i in dec:
        dec[i] += 1  # If it exists, increment the existing count
    else:
        dec[i] = 1   # If it's new, set it to 1

print(dec)

{1: 1, 2: 3, 3: 3, 4: 1}

__Q23. Create a Pandas DataFrame of product sales:__

    Product
    Price
    Quantity

Create a new column:

    Total = Price × Quantity

In [ ]:
data = {
    "Product":["Laptop","Mouse","Keyboead","Moniter"],
    "Price":[60000,300,1500,12000],
    "Quantity":[15,30,25,10]
}

shop = pd.DataFrame(data)
shop

    Product  Price  Quantity
0    Laptop  60000        15
1     Mouse    300        30
2  Keyboead   1500        25
3   Moniter  12000        10

In [ ]:
# Add new column Total_Sales

shop["Total_Sales"] = shop["Price"] *   shop["Quantity"]
shop

    Product  Price  Quantity  Total_Sales
0    Laptop  60000        15       900000
1     Mouse    300        30         9000
2  Keyboead   1500        25        37500
3   Moniter  12000        10       120000

__Q24. Write code to fill missing salary values with mean salary.__

In [ ]:
data = {
    'Name': ['Amit', 'Priya', 'Vikram', 'Neha', 'Sanjay'],
    'Department': ['IT', 'HR', 'IT', 'Marketing', 'Sales'],
    'Salary': [75000, np.nan, 82000, np.nan, 70000], # Notice the NaNs here
    'DOJ': ['2023-01-15', '2022-05-20', '2021-11-10', '2024-02-01', '2023-08-25']
}

emp = pd.DataFrame(data)
emp

     Name Department   Salary         DOJ
0    Amit         IT  75000.0  2023-01-15
1   Priya         HR      NaN  2022-05-20
2  Vikram         IT  82000.0  2021-11-10
3    Neha  Marketing      NaN  2024-02-01
4  Sanjay      Sales  70000.0  2023-08-25

In [ ]:
# Fill the missiong values in Salary column
emp = emp.fillna(emp["Salary"].mean())
emp

     Name Department        Salary         DOJ
0    Amit         IT  75000.000000  2023-01-15
1   Priya         HR  75666.666667  2022-05-20
2  Vikram         IT  82000.000000  2021-11-10
3    Neha  Marketing  75666.666667  2024-02-01
4  Sanjay      Sales  70000.000000  2023-08-25

In [ ]:
# Round of the salary with round of 2 decimal point
emp["Salary"] = emp["Salary"].round(2)
emp

     Name Department    Salary         DOJ
0    Amit         IT  75000.00  2023-01-15
1   Priya         HR  75666.67  2022-05-20
2  Vikram         IT  82000.00  2021-11-10
3    Neha  Marketing  75666.67  2024-02-01
4  Sanjay      Sales  70000.00  2023-08-25

__Q25. Using Pandas, find total sales per product.__

In [ ]:
shop

    Product  Price  Quantity  Total_Sales
0    Laptop  60000        15       900000
1     Mouse    300        30         9000
2  Keyboead   1500        25        37500
3   Moniter  12000        10       120000

In [ ]:
shop.groupby("Product")["Total_Sales"].sum().sort_values(ascending= False)

Product
Laptop      900000
Moniter     120000
Keyboead     37500
Mouse         9000
Name: Total_Sales, dtype: int64

<h2 style="color:Green; font-weight:bold;">Section D (5 Marks Questions.)</h2>

__Q26. Python Data Processing__

You are given a list of employee salaries:

    salaries = [45000, 52000, 48000, 60000, 75000, 50000, 62000]

Write a Python program to:

    1. Find the highest salary
    2. Find the lowest salary
    3. Calculate the average salary

Create a new list containing salaries greater than 55000

    Print all results clearly.

In [ ]:
salaries = [45000, 52000, 48000, 60000, 75000, 50000, 62000]

salaries.sort()
max = len(salaries) -1

print("The lowest salary is:- ",salaries[0])
print("The highest salary is:- ", salaries[max])
 
for i in salaries:
    i += i 
    avg = i / len(salaries)

avg = round(avg,2)
print("The average value of salary is:-", avg)

The lowest salary is:-  45000
The highest salary is:-  75000
The average value of salary is:- 21428.57

__Q27. Data Cleaning (Important)__

Create a DataFrame with some missing values:

    Name
    Age
    Salary
    City

Perform:

    Detect missing values
    Fill missing Age with mean
    Drop rows where Salary is missing

In [ ]:
data = {
    'Name': ['Amit', 'Priya', 'Vikram', 'Neha', 'Sanjay', 'Anjali', 'Rohan', 'Sneha', 'Kabir', 'Meera'],
    'Age': [25, np.nan, 30, 22, np.nan, 28, 35, np.nan, 40, 27],
    'Salary': [75000, 60000, np.nan, 55000, 70000, np.nan, 82000, 48000, np.nan, 65000],
    'City': ['Indore', 'Mumbai', 'Delhi', 'Pune', 'Indore', 'Bangalore', 'Chennai', 'Indore', 'Delhi', 'Mumbai']
}

dost = pd.DataFrame(data)
dost

     Name   Age   Salary       City
0    Amit  25.0  75000.0     Indore
1   Priya   NaN  60000.0     Mumbai
2  Vikram  30.0      NaN      Delhi
3    Neha  22.0  55000.0       Pune
4  Sanjay   NaN  70000.0     Indore
5  Anjali  28.0      NaN  Bangalore
6   Rohan  35.0  82000.0    Chennai
7   Sneha   NaN  48000.0     Indore
8   Kabir  40.0      NaN      Delhi
9   Meera  27.0  65000.0     Mumbai

In [ ]:
# Find missing value 
dost.isnull().sum()

Name      0
Age       3
Salary    3
City      0
dtype: int64

In [ ]:
# Fill null value in age with mean value 
dost["Age"] = dost["Age"].fillna(dost["Age"].mean())
dost

     Name        Age   Salary       City
0    Amit  25.000000  75000.0     Indore
1   Priya  29.571429  60000.0     Mumbai
2  Vikram  30.000000      NaN      Delhi
3    Neha  22.000000  55000.0       Pune
4  Sanjay  29.571429  70000.0     Indore
5  Anjali  28.000000      NaN  Bangalore
6   Rohan  35.000000  82000.0    Chennai
7   Sneha  29.571429  48000.0     Indore
8   Kabir  40.000000      NaN      Delhi
9   Meera  27.000000  65000.0     Mumbai

In [ ]:
# Round of value 
dost["Age"] = dost["Age"].round()
dost

     Name   Age   Salary       City
0    Amit  25.0  75000.0     Indore
1   Priya  30.0  60000.0     Mumbai
2  Vikram  30.0      NaN      Delhi
3    Neha  22.0  55000.0       Pune
4  Sanjay  30.0  70000.0     Indore
5  Anjali  28.0      NaN  Bangalore
6   Rohan  35.0  82000.0    Chennai
7   Sneha  30.0  48000.0     Indore
8   Kabir  40.0      NaN      Delhi
9   Meera  27.0  65000.0     Mumbai

In [ ]:
# Drop Rows where salary is missing 
dost = dost.dropna(subset= ["Salary"])
dost

     Name   Age   Salary     City
0    Amit  25.0  75000.0   Indore
1   Priya  30.0  60000.0   Mumbai
3    Neha  22.0  55000.0     Pune
4  Sanjay  30.0  70000.0   Indore
6   Rohan  35.0  82000.0  Chennai
7   Sneha  30.0  48000.0   Indore
9   Meera  27.0  65000.0   Mumbai

__Q28. Pandas Analysis__

Create a sales dataset:

    Product
    Category
    Price
    Quantity
    City

Tasks:

    1. Create column Revenue
    2. Find total revenue per product
    3. Find city with highest sales

In [ ]:
import random

# Setting up sample data to pick from
products = ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'USB Hub', 'Webcam', 'Headset', 'Printer']
categories = ['Electronics', 'Accessories', 'Peripherals']
cities = ['Indore', 'Mumbai', 'Delhi', 'Pune', 'Bangalore', 'Chennai']

# Generating 25 rows of data
data = {
    'Product': [random.choice(products) for _ in range(25)],
    'Category': [random.choice(categories) for _ in range(25)],
    'Quantity': [random.randint(1, 10) for _ in range(25)],
    'Price': [random.randint(500, 55000) for _ in range(25)],
    'City': [random.choice(cities) for _ in range(25)]
}

# Creating the DataFrame
sales = pd.DataFrame(data)
sales.head()

    Product     Category  Quantity  Price    City
0  Keyboard  Accessories         6  42772  Indore
1   Monitor  Electronics         5   9669   Delhi
2     Mouse  Accessories         2  45377  Indore
3    Webcam  Accessories         7  37282  Indore
4   Headset  Peripherals         6  20139  Indore

__Q29. Pandas Pivot Table__

Create a DataFrame of orders:

    Order_ID
    City
    Product
    Revenue

Create a pivot table showing:

    Rows → City
    Columns → Product
    Values → Revenue

In [12]:
data = {
    'Order_ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'City': ['Indore', 'Mumbai', 'Delhi', 'Pune', 'Indore', 'Mumbai', 'Delhi', 'Indore', 'Pune', 'Mumbai'],
    'Product': ['Laptop', 'Mouse', 'Monitor', 'Keyboard', 'Laptop', 'Monitor', 'Mouse', 'Keyboard', 'Laptop', 'Monitor'],
    'Revenue': [55000, 800, 12000, 1500, 52000, 12500, 900, 1600, 54000, 11800]
}

orders = pd.DataFrame(data)
orders.head()

   Order_ID    City   Product  Revenue
0       101  Indore    Laptop    55000
1       102  Mumbai     Mouse      800
2       103   Delhi   Monitor    12000
3       104    Pune  Keyboard     1500
4       105  Indore    Laptop    52000

In [13]:
# Create Pivot table 

pd.pivot_table(
    orders,
    index= "City",
    columns= "Product",
    values= "Revenue"
)

Product  Keyboard   Laptop  Monitor  Mouse
City
Delhi         NaN      NaN  12000.0  900.0
Indore     1600.0  53500.0      NaN    NaN
Mumbai        NaN      NaN  12150.0  800.0
Pune       1500.0  54000.0      NaN    NaN

<h2 style="color:Green; font-weight:bold;">Section E (8 Marks Questions.)</h2>

__Q30. Real Business Problem__

An online store has the following data:

    Customer
    Product
    Price
    Quantity
    City
    Rating

Tasks:

    1. Create Total_Sales = Price × Quantity
    2. Find top 3 customers by spending
    2. Find average rating per product
    4. Find city with highest revenue

In [14]:
customers = ['Aman', 'Sita', 'John', 'Riya', 'Zeeshan', 'Rahul', 'Priya', 'Ananya', 'Vikram', 'Sneha']
products = ['Smartphone', 'Earbuds', 'Charger', 'Smartwatch', 'Powerbank', 'Tablet', 'Case']
cities = ['Indore', 'Mumbai', 'Delhi', 'Pune', 'Bangalore']

# Generating 25 rows of data
data = {
    'Customer': [np.random.choice(customers) for _ in range(25)],
    'Product': [np.random.choice(products) for _ in range(25)],
    'Price': [np.random.choice([15000, 2500, 1000, 5000, 2000, 30000, 500]) for _ in range(25)],
    'Quantity': [np.random.randint(1, 5) for _ in range(25)],
    'City': [np.random.choice(cities) for _ in range(25)],
    'Rating': [np.random.randint(1, 6) for _ in range(25)]
}

store = pd.DataFrame(data)
store.head()

  Customer     Product  Price  Quantity    City  Rating
0     Riya     Earbuds   2500         4  Mumbai       3
1    Priya  Smartphone   2500         1   Delhi       4
2     John        Case    500         4    Pune       5
3   Vikram      Tablet   2000         4    Pune       2
4     Sita     Charger   1000         4  Indore       4

In [15]:
# Create total sales 
store["Total_Sales"] = store["Price"] * store["Quantity"]
store.head()

  Customer     Product  Price  Quantity    City  Rating  Total_Sales
0     Riya     Earbuds   2500         4  Mumbai       3        10000
1    Priya  Smartphone   2500         1   Delhi       4         2500
2     John        Case    500         4    Pune       5         2000
3   Vikram      Tablet   2000         4    Pune       2         8000
4     Sita     Charger   1000         4  Indore       4         4000

In [16]:
# Find top 3 customer by spending 
store.groupby("Customer")["Total_Sales"].sum().sort_values(ascending= False).head(3)

Customer
Sita     164000
Rahul    137500
John      62000
Name: Total_Sales, dtype: int64

In [18]:
# Find average rating per product 
store.groupby("Product")["Rating"].mean().sort_values(ascending= False).round(2)

Product
Case          5.00
Powerbank     4.50
Smartwatch    3.67
Smartphone    3.38
Tablet        3.00
Charger       2.60
Earbuds       2.00
Name: Rating, dtype: float64

In [19]:
# Find city with highest revenue 
store.groupby("City")["Total_Sales"].sum().sort_values(ascending= False)

City
Pune         235000
Indore       147000
Bangalore     77000
Mumbai        29500
Delhi         28500
Name: Total_Sales, dtype: int64

__Q31. Data Cleaning + Analysis__

Dataset:

    Order_ID
    Customer
    Product
    Price
    Quantity
    Order_Date
    City

But the dataset contains problems:

    Missing values
    Duplicate rows
    Wrong data types

Tasks:

    Remove duplicates
    Handle missing values
    Convert Order_Date to datetime
    Create column Revenue
    Find monthly revenue trend

In [65]:
data = {
    'Order_ID': [101, 102, 102, 103, 104, 105, 105, 106, 107, 108],
    'Customer': ['Aman', 'Sita', 'Sita', 'John', np.nan, 'Riya', 'Riya', 'Rahul', 'Priya', 'Vikram'],
    'Product': ['Laptop', 'Mouse', 'Mouse', 'Monitor', 'Keyboard', 'Laptop', 'Laptop', 'Monitor', np.nan, 'Mouse'],
    'Price': ['55000', '800', '800', '12000', '1500', '52000', '52000', '12500', '900', '800'], # String type (Wrong)
    'Quantity': [1, 2, 2, np.nan, 1, 1, 1, 2, 3, np.nan],
    'Order_Date': ['2024-01-01', '2024-01-02', '2024-01-02', '2024-01-03', '2024-01-04', '2024-01-05', '2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08'],
    'City': ['Indore', 'Mumbai', 'Mumbai', 'Delhi', 'Pune', 'Indore', 'Indore', 'Mumbai', 'Delhi', 'Indore']
}

sales = pd.DataFrame(data)
sales

   Order_ID Customer   Product  Price  Quantity  Order_Date    City
0       101     Aman    Laptop  55000       1.0  2024-01-01  Indore
1       102     Sita     Mouse    800       2.0  2024-01-02  Mumbai
2       102     Sita     Mouse    800       2.0  2024-01-02  Mumbai
3       103     John   Monitor  12000       NaN  2024-01-03   Delhi
4       104      NaN  Keyboard   1500       1.0  2024-01-04    Pune
5       105     Riya    Laptop  52000       1.0  2024-01-05  Indore
6       105     Riya    Laptop  52000       1.0  2024-01-05  Indore
7       106    Rahul   Monitor  12500       2.0  2024-01-06  Mumbai
8       107    Priya       NaN    900       3.0  2024-01-07   Delhi
9       108   Vikram     Mouse    800       NaN  2024-01-08  Indore

In [80]:
sales.duplicated()

0    False
1    False
3    False
4    False
5    False
7    False
8    False
9    False
dtype: bool

In [67]:
# Remove duplicates
sales = sales.drop_duplicates()

In [79]:
# Handling missing values 
sales.isnull().sum()

Order_ID      0
Customer      0
Product       0
Price         0
Quantity      0
Order_Date    0
City          0
Revenue       0
dtype: int64

In [69]:
# Handle missing value
# 1st Customer name into user
sales["Customer"] = sales["Customer"].fillna("User")

C:\Users\pushp\AppData\Local\Temp\ipykernel_15532\2743071508.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales["Customer"] = sales["Customer"].fillna("User")

In [71]:
# 2nd change product into unknown_product
sales["Product"] = sales["Product"].fillna("Unknown_Product")

C:\Users\pushp\AppData\Local\Temp\ipykernel_15532\2491368264.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales["Product"] = sales["Product"].fillna("Unknown_Product")

In [72]:
# 3rd change missing quantity value with the help of mean 
sales["Quantity"] = sales["Quantity"].fillna(sales["Quantity"].mean())

C:\Users\pushp\AppData\Local\Temp\ipykernel_15532\1501375455.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales["Quantity"] = sales["Quantity"].fillna(sales["Quantity"].mean())

In [73]:
# Round of Quantity value
sales["Quantity"] = round(sales["Quantity"])

C:\Users\pushp\AppData\Local\Temp\ipykernel_15532\3643326871.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales["Quantity"] = round(sales["Quantity"])

In [74]:
sales.head()

   Order_ID Customer   Product  Price  Quantity  Order_Date    City
0       101     Aman    Laptop  55000       1.0  2024-01-01  Indore
1       102     Sita     Mouse    800       2.0  2024-01-02  Mumbai
3       103     John   Monitor  12000       2.0  2024-01-03   Delhi
4       104     User  Keyboard   1500       1.0  2024-01-04    Pune
5       105     Riya    Laptop  52000       1.0  2024-01-05  Indore

In [78]:
# Data cleaning 
# 1. Data type 

sales.dtypes

Order_ID               int64
Customer              object
Product               object
Price                  int64
Quantity             float64
Order_Date    datetime64[ns]
City                  object
Revenue              float64
dtype: object

In [76]:
# We saw 2 problem in data type 
# 1. one in price column is object type and we will try to change into int 
# 2. Second one is order date is also object type and we will try to change into datetime 

sales["Price"] = sales["Price"].astype(int)
sales["Order_Date"] = pd.to_datetime(sales["Order_Date"])
sales

C:\Users\pushp\AppData\Local\Temp\ipykernel_15532\3683652754.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales["Price"] = sales["Price"].astype(int)
C:\Users\pushp\AppData\Local\Temp\ipykernel_15532\3683652754.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales["Order_Date"] = pd.to_datetime(sales["Order_Date"])

   Order_ID Customer          Product  Price  Quantity Order_Date    City
0       101     Aman           Laptop  55000       1.0 2024-01-01  Indore
1       102     Sita            Mouse    800       2.0 2024-01-02  Mumbai
3       103     John          Monitor  12000       2.0 2024-01-03   Delhi
4       104     User         Keyboard   1500       1.0 2024-01-04    Pune
5       105     Riya           Laptop  52000       1.0 2024-01-05  Indore
7       106    Rahul          Monitor  12500       2.0 2024-01-06  Mumbai
8       107    Priya  Unknown_Product    900       3.0 2024-01-07   Delhi
9       108   Vikram            Mouse    800       2.0 2024-01-08  Indore

In [77]:
# Create column Revenue 
sales["Revenue"] = sales["Price"] * sales["Quantity"]
sales.head()

C:\Users\pushp\AppData\Local\Temp\ipykernel_15532\1230915342.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales["Revenue"] = sales["Price"] * sales["Quantity"]

   Order_ID Customer   Product  Price  Quantity Order_Date    City  Revenue
0       101     Aman    Laptop  55000       1.0 2024-01-01  Indore  55000.0
1       102     Sita     Mouse    800       2.0 2024-01-02  Mumbai   1600.0
3       103     John   Monitor  12000       2.0 2024-01-03   Delhi  24000.0
4       104     User  Keyboard   1500       1.0 2024-01-04    Pune   1500.0
5       105     Riya    Laptop  52000       1.0 2024-01-05  Indore  52000.0

In [ ]:
# Create Month_Name column
sales["Month_Name"] = sales["Order_Date"].dt.month_name()
sales.head()

C:\Users\pushp\AppData\Local\Temp\ipykernel_15532\2023143012.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sales["Month_Name"] = sales["Order_Date"].dt.month_name()

,Order_ID,Customer,Product,Price,Quantity,Order_Date,City,Revenue,Month_Name
0,101,Aman,Laptop,55000,1.0,2024-01-01,Indore,55000.0,January
1,102,Sita,Mouse,800,2.0,2024-01-02,Mumbai,1600.0,January
3,103,John,Monitor,12000,2.0,2024-01-03,Delhi,24000.0,January
4,104,User,Keyboard,1500,1.0,2024-01-04,Pune,1500.0,January
5,105,Riya,Laptop,52000,1.0,2024-01-05,Indore,52000.0,January

In [83]:
# Find Monthly Revenue 
sales.groupby("Month_Name")["Revenue"].sum()

Month_Name
January    163400.0
Name: Revenue, dtype: float64

In [84]:
sales

,Order_ID,Customer,Product,Price,Quantity,Order_Date,City,Revenue,Month_Name
0,101,Aman,Laptop,55000,1.0,2024-01-01,Indore,55000.0,January
1,102,Sita,Mouse,800,2.0,2024-01-02,Mumbai,1600.0,January
3,103,John,Monitor,12000,2.0,2024-01-03,Delhi,24000.0,January
4,104,User,Keyboard,1500,1.0,2024-01-04,Pune,1500.0,January
5,105,Riya,Laptop,52000,1.0,2024-01-05,Indore,52000.0,January
7,106,Rahul,Monitor,12500,2.0,2024-01-06,Mumbai,25000.0,January
8,107,Priya,Unknown_Product,900,3.0,2024-01-07,Delhi,2700.0,January
9,108,Vikram,Mouse,800,2.0,2024-01-08,Indore,1600.0,January