<h2 style="color:darkorange; font-weight:bold;">Mid-Level Pandas Quesions</h2>

In [1]:
import pandas as pd

## Create Data frame

In [6]:
data = {
    "order_id": [101,102,103,104,105,106,107,108,109,110],
    "customer_name": ["Aman","Riya","Rahul","Sneha","Aman","Karan","Riya","Rahul","Sneha","Aman"],
    "city": ["Delhi","Mumbai","Delhi","Bangalore","Mumbai","Delhi","Bangalore","Mumbai","Delhi","Bangalore"],
    "product": ["Laptop","Phone","Tablet","Laptop","Phone","Tablet","Laptop","Phone","Tablet","Laptop"],
    "category": ["Electronics","Electronics","Electronics","Electronics","Electronics","Electronics","Electronics","Electronics","Electronics","Electronics"],
    "quantity": [1,2,1,1,3,2,1,2,1,1],
    "price": [60000,20000,30000,65000,21000,28000,62000,19000,31000,64000],
    "order_date": [
        "2024-01-02","2024-01-05","2024-01-07","2024-01-10","2024-01-12",
        "2024-01-15","2024-01-18","2024-01-20","2024-01-23","2024-01-25"
    ]
}

df = pd.DataFrame(data)

In [7]:
df.head()

,order_id,customer_name,city,product,category,quantity,price,order_date
0,101,Aman,Delhi,Laptop,Electronics,1,60000,2024-01-02
1,102,Riya,Mumbai,Phone,Electronics,2,20000,2024-01-05
2,103,Rahul,Delhi,Tablet,Electronics,1,30000,2024-01-07
3,104,Sneha,Bangalore,Laptop,Electronics,1,65000,2024-01-10
4,105,Aman,Mumbai,Phone,Electronics,3,21000,2024-01-12

<h2 style="color:Red; font-weight:bold;">Practice Questions</h2>

__Q1. Create a new column called revenue.__

In [12]:
df["revenue"] = df["quantity"] * df["price"]
df.head()

,order_id,customer_name,city,product,category,quantity,price,order_date,revenue
0,101,Aman,Delhi,Laptop,Electronics,1,60000,2024-01-02,60000
1,102,Riya,Mumbai,Phone,Electronics,2,20000,2024-01-05,40000
2,103,Rahul,Delhi,Tablet,Electronics,1,30000,2024-01-07,30000
3,104,Sneha,Bangalore,Laptop,Electronics,1,65000,2024-01-10,65000
4,105,Aman,Mumbai,Phone,Electronics,3,21000,2024-01-12,63000

__Q2. Find the total revenue generated by each city.__

In [ ]:
df.groupby("city")["revenue"].sum().sort_values(ascending= True)

city
Bangalore    191000
Delhi        177000
Mumbai       141000
Name: revenue, dtype: int64

__Q3. Find the top 3 customers who spent the most money.__

In [22]:
df.groupby("customer_name")["revenue"].sum().sort_values(ascending= False).head(3)

customer_name
Aman     187000
Riya     102000
Sneha     96000
Name: revenue, dtype: int64

__Q4. Find the average order value for each product.__

In [45]:
aov = df.groupby("product")[["revenue","quantity"]].sum()
aov["AOV"] = aov["revenue"] / aov["quantity"]
aov

         revenue  quantity           AOV
product
Laptop    251000         4  62750.000000
Phone     141000         7  20142.857143
Tablet    117000         4  29250.000000

__Q5. Find the total quantity sold for each product.__

In [48]:
df.groupby("product")["quantity"].sum().sort_values(ascending= False)

product
Phone     7
Laptop    4
Tablet    4
Name: quantity, dtype: int64

__Q6. Find which city ordered the highest number of products.__

In [49]:
df.head()

,order_id,customer_name,city,product,category,quantity,price,order_date,revenue
0,101,Aman,Delhi,Laptop,Electronics,1,60000,2024-01-02,60000
1,102,Riya,Mumbai,Phone,Electronics,2,20000,2024-01-05,40000
2,103,Rahul,Delhi,Tablet,Electronics,1,30000,2024-01-07,30000
3,104,Sneha,Bangalore,Laptop,Electronics,1,65000,2024-01-10,65000
4,105,Aman,Mumbai,Phone,Electronics,3,21000,2024-01-12,63000

In [51]:
df.groupby("city")["quantity"].sum().sort_values(ascending= False)

city
Mumbai       7
Delhi        5
Bangalore    3
Name: quantity, dtype: int64

__Q7. Find the day with the highest revenue.__

In [53]:
df.groupby("order_date")["revenue"].sum().sort_values(ascending= False).head(5)

order_date
2024-01-10    65000
2024-01-25    64000
2024-01-12    63000
2024-01-18    62000
2024-01-02    60000
Name: revenue, dtype: int64

__Q8. Find customers who placed more than 1 order.__

In [55]:
cust = df.groupby("customer_name")["customer_name"].count().sort_values(ascending= False)
repeatable_customer = cust[cust > 1]
repeatable_customer

customer_name
Aman     3
Rahul    2
Riya     2
Sneha    2
Name: customer_name, dtype: int64

__Q9. Create a pivot table showing:__

    Rows → city  
    Columns → product  
    Values → total revenue

In [67]:
product_data = pd.pivot_table(
    df,
    index= "city",
    columns= "product",
    values= "revenue",
    aggfunc= "sum"
)

In [68]:
product_data

product      Laptop     Phone    Tablet
city
Bangalore  191000.0       NaN       NaN
Delhi       60000.0       NaN  117000.0
Mumbai          NaN  141000.0       NaN

__Fill null value__

In [69]:
product_data["Laptop"] = product_data["Laptop"].fillna(0)

In [71]:
product_data["Phone"] = product_data["Phone"].fillna(0)

In [72]:
product_data["Tablet"] = product_data["Tablet"].fillna(0)

In [73]:
product_data

product      Laptop     Phone    Tablet
city
Bangalore  191000.0       0.0       0.0
Delhi       60000.0       0.0  117000.0
Mumbai          0.0  141000.0       0.0

__Q10 Find the percentage contribution of each product to total revenue.__

Example output idea:

    Product	          Revenue %
    Laptop	         55%
    Phone	         30%
    Tablet	         15%

In [74]:
df["revenue_percentage"] = (df["revenue"] / df["revenue"].sum()) * 100

In [86]:
df["Revenue_Percentage"] = round(((df["revenue"] / df["revenue"].sum()) * 100),2)
df

,order_id,customer_name,city,product,category,quantity,price,order_date,revenue,revenue_percentage,Revenue_Percentage
0,101,Aman,Delhi,Laptop,Electronics,1,60000,2024-01-02,60000,11.787819,11.79
1,102,Riya,Mumbai,Phone,Electronics,2,20000,2024-01-05,40000,7.858546,7.86
2,103,Rahul,Delhi,Tablet,Electronics,1,30000,2024-01-07,30000,5.893910,5.89
3,104,Sneha,Bangalore,Laptop,Electronics,1,65000,2024-01-10,65000,12.770138,12.77
4,105,Aman,Mumbai,Phone,Electronics,3,21000,2024-01-12,63000,12.377210,12.38
5,106,Karan,Delhi,Tablet,Electronics,2,28000,2024-01-15,56000,11.001965,11.00
6,107,Riya,Bangalore,Laptop,Electronics,1,62000,2024-01-18,62000,12.180747,12.18
7,108,Rahul,Mumbai,Phone,Electronics,2,19000,2024-01-20,38000,7.465619,7.47
8,109,Sneha,Delhi,Tablet,Electronics,1,31000,2024-01-23,31000,6.090373,6.09
9,110,Aman,Bangalore,Laptop,Electronics,1,64000,2024-01-25,64000,12.573674,12.57

In [90]:
df.groupby("product")["Revenue_Percentage"].sum().astype(str) + "%"

product
Laptop    49.31%
Phone     27.71%
Tablet    22.98%
Name: Revenue_Percentage, dtype: object

__Q11. Find customers who purchased from more than one city.__

Example:

    Aman → Delhi + Mumbai + Bangalore

In [ ]:
customer = df.groupby("customer_name")["city"].count()
customer_city = customer[customer > 1]
customer_city

customer_name
Aman     3
Rahul    2
Riya     2
Sneha    2
Name: city, dtype: int64

In [100]:
cust1 = pd.pivot_table(
    df,
    index="customer_name",
    columns="city",
    values="product",
    aggfunc="count"
)
cust1

city           Bangalore  Delhi  Mumbai
customer_name
Aman                 1.0    1.0     1.0
Karan                NaN    1.0     NaN
Rahul                NaN    1.0     1.0
Riya                 1.0    NaN     1.0
Sneha                1.0    1.0     NaN

In [107]:
multi_city_customers = cust1.dropna(thresh=2)

In [108]:
multi_city_customers

city           Bangalore  Delhi  Mumbai
customer_name
Aman                 1.0    1.0     1.0
Rahul                NaN    1.0     1.0
Riya                 1.0    NaN     1.0
Sneha                1.0    1.0     NaN

In [ ]:
# 2nd way to solve this quesiton 
df.groupby("customer_name")["city"].unique().reset_index()

  customer_name                        city
0          Aman  [Delhi, Mumbai, Bangalore]
1         Karan                     [Delhi]
2         Rahul             [Delhi, Mumbai]
3          Riya         [Mumbai, Bangalore]
4         Sneha          [Bangalore, Delhi]

Find the most profitable city for Laptop sales.

    Steps hint:

        Filter Laptop
        Calculate revenue
        Group by city

In [115]:
df.head(5)

,order_id,customer_name,city,product,category,quantity,price,order_date,revenue,revenue_percentage,Revenue_Percentage
0,101,Aman,Delhi,Laptop,Electronics,1,60000,2024-01-02,60000,11.787819,11.79
1,102,Riya,Mumbai,Phone,Electronics,2,20000,2024-01-05,40000,7.858546,7.86
2,103,Rahul,Delhi,Tablet,Electronics,1,30000,2024-01-07,30000,5.893910,5.89
3,104,Sneha,Bangalore,Laptop,Electronics,1,65000,2024-01-10,65000,12.770138,12.77
4,105,Aman,Mumbai,Phone,Electronics,3,21000,2024-01-12,63000,12.377210,12.38

In [120]:
laptop_product = df[df["product"] == "Laptop"]
laptop_product

,order_id,customer_name,city,product,category,quantity,price,order_date,revenue,revenue_percentage,Revenue_Percentage
0,101,Aman,Delhi,Laptop,Electronics,1,60000,2024-01-02,60000,11.787819,11.79
3,104,Sneha,Bangalore,Laptop,Electronics,1,65000,2024-01-10,65000,12.770138,12.77
6,107,Riya,Bangalore,Laptop,Electronics,1,62000,2024-01-18,62000,12.180747,12.18
9,110,Aman,Bangalore,Laptop,Electronics,1,64000,2024-01-25,64000,12.573674,12.57

In [121]:
laptop_product.groupby("city")["revenue"].sum()

city
Bangalore    191000
Delhi         60000
Name: revenue, dtype: int64

In [125]:
df.head(5)

,order_id,customer_name,city,product,category,quantity,price,order_date,revenue,revenue_percentage,Revenue_Percentage
0,101,Aman,Delhi,Laptop,Electronics,1,60000,2024-01-02,60000,11.787819,11.79
1,102,Riya,Mumbai,Phone,Electronics,2,20000,2024-01-05,40000,7.858546,7.86
2,103,Rahul,Delhi,Tablet,Electronics,1,30000,2024-01-07,30000,5.893910,5.89
3,104,Sneha,Bangalore,Laptop,Electronics,1,65000,2024-01-10,65000,12.770138,12.77
4,105,Aman,Mumbai,Phone,Electronics,3,21000,2024-01-12,63000,12.377210,12.38

__Drop unwanted Column name "revenue_percentage"__

In [130]:
df.drop("revenue_percentage", axis= 1, inplace= True)

In [131]:
df.head()

,order_id,customer_name,city,product,category,quantity,price,order_date,revenue,Revenue_Percentage
0,101,Aman,Delhi,Laptop,Electronics,1,60000,2024-01-02,60000,11.79
1,102,Riya,Mumbai,Phone,Electronics,2,20000,2024-01-05,40000,7.86
2,103,Rahul,Delhi,Tablet,Electronics,1,30000,2024-01-07,30000,5.89
3,104,Sneha,Bangalore,Laptop,Electronics,1,65000,2024-01-10,65000,12.77
4,105,Aman,Mumbai,Phone,Electronics,3,21000,2024-01-12,63000,12.38