<h2 style="color:darkorange; font-weight:bold;">Pandas</h2>

<h2 style="color:Red; font-weight:bold;">Day 1</h2>

## What is Pandas

Pandas is an open-source Python library designed specifically for data manipulation and structured data analysis. It was created by Wes McKinney to solve real-world financial data problems, and today it has become the backbone of data analysis in Python.

At its core, Pandas provides high-level data structures and tools that allow us to work with structured datasets efficiently. It is built on top of NumPy, which means it inherits NumPy’s speed and array-processing power but adds labeled axes (rows and columns), making data much easier to understand and manipulate.

Unlike plain Python lists or dictionaries, Pandas is optimized for:

    Tabular data (rows and columns)
    Handling missing values
    Performing statistical operations
    Working with time series data
    Reading and writing different file formats

The two primary data structures in Pandas are:

    Series (1D labeled array)
    DataFrame (2D labeled data structure)

In simple terms:

    Pandas = Powerful tool to clean, transform, and analyze structured data efficiently.

## Why Pandas is Extremely Useful for a Data Analyst

A Data Analyst spends most of their time not building dashboards but cleaning and preparing data. Real-world data is messy, inconsistent, incomplete, and unstructured. Pandas solves these issues systematically.

Let’s understand practically.

Imagine you receive a sales CSV file from a company. It may contain:

    Missing values
    Duplicate records
    Incorrect data types
    Mixed formatting
    Unnecessary columns

Without Pandas, cleaning this manually would be extremely slow and error-prone.

Pandas helps in:

    Data cleaning (handling NaN, duplicates)
    Data transformation (creating new columns)
    Data aggregation (sum, mean, groupby)
    Data filtering
    Data merging (like SQL joins)
    Data exporting

For a Data Analyst, Pandas replaces 70% of Excel work and provides scalability for millions of rows.

Important insight:

    Pandas bridges the gap between raw data and meaningful insights.

<h2 style="color:darkorange; font-weight:bold;">Data Frame</h2>

A DataFrame is the most important object in Pandas. It is a two-dimensional, size-mutable, heterogeneous tabular data structure with labeled axes.

Let’s break that definition carefully.

    Two-dimensional:
    It has rows and columns.

    Size-mutable:
    You can add or remove rows and columns dynamically.

    Heterogeneous:
    Each column can have different data types.

    Labeled axes:
    Both rows and columns have labels.

Internally, a DataFrame is built from multiple Series objects. Each column in a DataFrame is a Series. So technically:

    DataFrame = Collection of aligned Series sharing the same index.

This alignment feature is very powerful. If you perform operations between two columns, Pandas aligns them based on index automatically.

Example structure conceptually:

    Index → Row labels
    Columns → Column labels
    Values → Data stored in NumPy arrays internally

Internally, Pandas stores data in blocks for performance optimization. Numeric columns are often grouped together for vectorized computation.

Key properties of a DataFrame:

    It is built on NumPy arrays.

    It supports vectorized operations.

    It automatically handles missing values.

    It supports powerful indexing mechanisms.

This makes DataFrame far superior to basic Python lists for data analysis.

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame([12,23,43,44], columns = ["Col_name"])
print(df)

   Col_name
0        12
1        23
2        43
3        44

In [1]:
data = {
    "Name": ["Pushpkar Roy", "Ankit Roy", "Anurag Pal", "Piyush panday","Praveen kumar","Siddhant sharma"],
    "Age":[22,26,21,23,22,22],
    "Salary":[56000,45000,51000,22000,36000,40000],
    "City": ["Jabalpur","Pune","Delhi","Jabalpur","Pune","Channi"]
}

In [4]:
df = pd.DataFrame(data)
print(df)

              Name  Age  Salary      City
0     Pushpkar Roy   22   56000  Jabalpur
1        Ankit Roy   26   45000      Pune
2       Anurag Pal   21   51000     Delhi
3    Piyush panday   23   22000  Jabalpur
4    Praveen kumar   22   36000      Pune
5  Siddhant sharma   22   40000    Channi

In [5]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

<h2 style="color:darkorange; font-weight:bold;">Basic dataframe understanding </h2>

__head() and tail()__

These methods allow quick preview of data. By default, they show 5 rows. This helps analysts understand the structure before deeper operations.

In [6]:
df.head()  #Top 5 Row of the data

            Name  Age  Salary      City
0   Pushpkar Roy   22   56000  Jabalpur
1      Ankit Roy   26   45000      Pune
2     Anurag Pal   21   51000     Delhi
3  Piyush panday   23   22000  Jabalpur
4  Praveen kumar   22   36000      Pune

In [7]:
df.tail()  #Last 5 Row of the data

              Name  Age  Salary      City
1        Ankit Roy   26   45000      Pune
2       Anurag Pal   21   51000     Delhi
3    Piyush panday   23   22000  Jabalpur
4    Praveen kumar   22   36000      Pune
5  Siddhant sharma   22   40000    Channi

__shape__

    Returns a tuple representing number of rows and columns.
    This is useful to understand dataset size instantly.

In [8]:
df.shape   # not using () brackate's 
           # show how many Rows and columns in the data   
           # Example (6,4) mean 6 Rows and 4 columns in this dataframe

(6, 4)

__columns__

    Returns column labels. Important for selecting and manipulating specific columns.

In [9]:
df.columns   # Show all columns names

Index(['Name', 'Age', 'Salary', 'City'], dtype='object')

__dtypes__

Shows data types of each column. This is critical because wrong data types can cause incorrect analysis.

    For example:

        Numbers stored as object (string) will break aggregation.
        Dates stored as string will break time analysis.

In [10]:
df.dtypes

Name      object
Age        int64
Salary     int64
City      object
dtype: object

In [11]:
df.rename(columns= {"Salary":"Monthly_Salary"}, inplace= True)  #Using Inplace = True for permanent change 
                                                                #If we are not using Inplace = True then they are not change the name permanently

In [12]:
df

              Name  Age  Monthly_Salary      City
0     Pushpkar Roy   22           56000  Jabalpur
1        Ankit Roy   26           45000      Pune
2       Anurag Pal   21           51000     Delhi
3    Piyush panday   23           22000  Jabalpur
4    Praveen kumar   22           36000      Pune
5  Siddhant sharma   22           40000    Channi

__info()__

One of the most powerful inspection tools.

    It shows:

        Number of non-null values
        Data types
        Memory usage

From info(), analysts quickly identify missing values and data type issues.

In [13]:
df.info()   #Show the information like Data type, null value and how many value in the column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            6 non-null      object
 1   Age             6 non-null      int64
 2   Monthly_Salary  6 non-null      int64
 3   City            6 non-null      object
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

__describe()__

Provides statistical summary for numeric columns:

    Count
    Mean
    Standard deviation
    Min and max
    Percentiles

This is often the first step in exploratory data analysis (EDA).

In [14]:
df.describe()  #Show the mean mode and other calculation for Int value of the data

             Age  Monthly_Salary
count   6.000000        6.000000
mean   22.666667    41666.666667
std     1.751190    12044.362443
min    21.000000    22000.000000
25%    22.000000    37000.000000
50%    22.000000    42500.000000
75%    22.750000    49500.000000
max    26.000000    56000.000000

<h2 style="color:darkorange; font-weight:bold;">Save and load data from CSV</h2>

## How to save data in CSV file

In [15]:
df.to_csv("My_first_data_for_timepass.csv")   #In the end of the name usine .csv is very important to save your data into csv file

## How to load CSV file data

In [16]:
load_df = pd.read_csv("My_first_data_for_timepass.csv")

In [17]:
load_df.head()

   Unnamed: 0           Name  Age  Monthly_Salary      City
0           0   Pushpkar Roy   22           56000  Jabalpur
1           1      Ankit Roy   26           45000      Pune
2           2     Anurag Pal   21           51000     Delhi
3           3  Piyush panday   23           22000  Jabalpur
4           4  Praveen kumar   22           36000      Pune

<h2 style="color:darkorange; font-weight:bold;">Rows & Columns - Selection</h2>

__Understanding Selection in Pandas__

In Pandas, selecting rows and columns is one of the most fundamental and frequently used operations. Every data analysis task involves extracting specific parts of data based on business requirements. Unlike Excel, where we manually select cells, Pandas provides powerful indexing and filtering mechanisms that are programmatic, scalable, and extremely flexible.

[]

.loc[]

.iloc[]

Each has a specific purpose.

In [18]:
# Select Columns 
load_df[["Name"]]
load_df[["Name","Monthly_Salary"]]

              Name  Monthly_Salary
0     Pushpkar Roy           56000
1        Ankit Roy           45000
2       Anurag Pal           51000
3    Piyush panday           22000
4    Praveen kumar           36000
5  Siddhant sharma           40000

Rows are selected differently. Pandas does not directly allow row selection using simple bracket notation.

For rows, we use:

    .loc[] → Label-based selection
    .iloc[] → Position-based selection

In [19]:
load_df.loc[0:3]   # [0:3] they include all value from 0 to 3. 3 is also included 
                    # .loc[] selects data based on row and column labels.

   Unnamed: 0           Name  Age  Monthly_Salary      City
0           0   Pushpkar Roy   22           56000  Jabalpur
1           1      Ankit Roy   26           45000      Pune
2           2     Anurag Pal   21           51000     Delhi
3           3  Piyush panday   23           22000  Jabalpur

In [20]:
# Select Rows
# loc - index name based
load_df.loc[load_df.Name == "Pushpkar Roy"]  # Using loc formula to excess the Row and using [].

# using double filter 

load_df.loc[(load_df.Name == "Ankit Roy") & (load_df.Age >= 20)]

   Unnamed: 0       Name  Age  Monthly_Salary  City
1           1  Ankit Roy   26           45000  Pune

In [21]:
# iloc = index value baded 

load_df.iloc[0]    # 0 is the index value mean 1 value of the table 
load_df.iloc[0:3]  # [o:3] They show all value between 0 to 3. 3 is not included 
                    #[start:stop:step]
                    # .iloc[] selects data based on numerical position.

   Unnamed: 0          Name  Age  Monthly_Salary      City
0           0  Pushpkar Roy   22           56000  Jabalpur
1           1     Ankit Roy   26           45000      Pune
2           2    Anurag Pal   21           51000     Delhi

__Difference Between loc and iloc (Core Concept)__

Feature_____________________________loc___________________________iloc

Based On___________________________Labels_________________________Position

Slice End_________________________Inclusive________________________Exclusive

Works With_______________________Index names_______________________Index numbers

<h2 style="color:darkorange; font-weight:bold;">Filter Dataframe</h2>

Filtering means selecting rows based on a condition.

This is where Pandas becomes extremely powerful.

In [22]:
df = load_df

Multiple Conditions in Filtering

Use:

    & → AND
    | → OR
    ~ → NOT

In [23]:
# Single filter
df[df["Age"] > 22]

   Unnamed: 0           Name  Age  Monthly_Salary      City
1           1      Ankit Roy   26           45000      Pune
3           3  Piyush panday   23           22000  Jabalpur

In [24]:
# Double and multiple filter 

df[(df["Age"] > 21) & (df["Monthly_Salary"] > 45000)]

   Unnamed: 0          Name  Age  Monthly_Salary      City
0           0  Pushpkar Roy   22           56000  Jabalpur

In [25]:
df[(df["Age"] >= 22) & (df["Monthly_Salary"]>= 40000)]

   Unnamed: 0             Name  Age  Monthly_Salary      City
0           0     Pushpkar Roy   22           56000  Jabalpur
1           1        Ankit Roy   26           45000      Pune
5           5  Siddhant sharma   22           40000    Channi

__isin() Method (Advanced Filtering)__

Used when filtering multiple values.

Example:

In [26]:
df[df["City"].isin(["Delhi", "Mumbai"])]

   Unnamed: 0        Name  Age  Monthly_Salary   City
2           2  Anurag Pal   21           51000  Delhi

In [27]:
df.where((df["Age"] >= 22))              # Cover not match columns with NaN values

   Unnamed: 0             Name   Age  Monthly_Salary      City
0         0.0     Pushpkar Roy  22.0         56000.0  Jabalpur
1         1.0        Ankit Roy  26.0         45000.0      Pune
2         NaN              NaN   NaN             NaN       NaN
3         3.0    Piyush panday  23.0         22000.0  Jabalpur
4         4.0    Praveen kumar  22.0         36000.0      Pune
5         5.0  Siddhant sharma  22.0         40000.0    Channi

In [28]:
df.where((df["Age"] >= 23), other= "Not Eligible") # replace NaN value with Not Eligible

     Unnamed: 0           Name           Age Monthly_Salary          City
0  Not Eligible   Not Eligible  Not Eligible   Not Eligible  Not Eligible
1             1      Ankit Roy            26          45000          Pune
2  Not Eligible   Not Eligible  Not Eligible   Not Eligible  Not Eligible
3             3  Piyush panday            23          22000      Jabalpur
4  Not Eligible   Not Eligible  Not Eligible   Not Eligible  Not Eligible
5  Not Eligible   Not Eligible  Not Eligible   Not Eligible  Not Eligible

<h2 style="color:darkorange; font-weight:bold;">Rows and columns - Operation (add, update, delete)</h2>

__DataFrame is mutable. That means we can:__

    Add rows
    Add columns
    Update values
    Delete rows
    Delete columns
    Drop data conditionally

Understanding internal behavior is very important because Pandas does not modify data in-place by default in many cases.

## Add new Columns

In [29]:
df

   Unnamed: 0             Name  Age  Monthly_Salary      City
0           0     Pushpkar Roy   22           56000  Jabalpur
1           1        Ankit Roy   26           45000      Pune
2           2       Anurag Pal   21           51000     Delhi
3           3    Piyush panday   23           22000  Jabalpur
4           4    Praveen kumar   22           36000      Pune
5           5  Siddhant sharma   22           40000    Channi

In [30]:
df["Team"] = ["Data Analyst","HR","BDE","Cloud AI", "HR","Coliud AI"]   # Add new columns with the name of team and based on work Role

In [31]:
df

   Unnamed: 0             Name  Age  Monthly_Salary      City          Team
0           0     Pushpkar Roy   22           56000  Jabalpur  Data Analyst
1           1        Ankit Roy   26           45000      Pune            HR
2           2       Anurag Pal   21           51000     Delhi           BDE
3           3    Piyush panday   23           22000  Jabalpur      Cloud AI
4           4    Praveen kumar   22           36000      Pune            HR
5           5  Siddhant sharma   22           40000    Channi     Coliud AI

In [ ]:
df

,Name,Age,Monthly_Salary,City,Team,Bonus,Salary
6,Pushpkar Roy,22,NaN,Jabalpur,Data Analyst,NaN,56000.0
7,Ankit Roy,26,NaN,Pune,HR,NaN,45000.0
8,Anurag Pal,21,NaN,Delhi,BDE,NaN,51000.0
9,Piyush panday,23,NaN,Jabalpur,Cloud AI,NaN,22000.0
10,Praveen kumar,22,NaN,Pune,HR,NaN,36000.0
11,Siddhant sharma,22,NaN,Channi,Coliud AI,NaN,40000.0

## Add new Row

__⚠ Important:__

Adding rows one by one is slow because DataFrame memory must be reallocated.

Professional approach for multiple rows:

In [ ]:
new_df = pd.DataFrame(data)
df = pd.concat([df, new_df], ignore_index=True)

In [ ]:
df

,Unnamed: 0,Name,Age,Monthly_Salary,City,Team,Bonus
0,0,Pushpkar Roy,22,56000,Jabalpur,Data Analyst,11200.0
1,1,Ankit Roy,26,45000,Pune,HR,9000.0
2,2,Anurag Pal,21,51000,Delhi,BDE,10200.0
3,3,Piyush panday,23,22000,Jabalpur,Cloud AI,4400.0
4,4,Praveen kumar,22,36000,Pune,HR,7200.0
5,5,Siddhant sharma,22,40000,Channi,Coliud AI,8000.0
6,6,Harsh soni,25,50000,Channi,BDE,10000.0

## Update value

In [ ]:
# Update value - using index name 
df.loc[6,"Name"] = "Pankaj Meena"
df.loc[6,"Team"] = "BDE"

In [ ]:
df

,Unnamed: 0,Name,Age,Monthly_Salary,City,Team,Bonus
0,0,Pushpkar Roy,22,56000,Jabalpur,Data Analyst,11200.0
1,1,Ankit Roy,26,45000,Pune,HR,9000.0
2,2,Anurag Pal,21,51000,Delhi,BDE,10200.0
3,3,Piyush panday,23,22000,Jabalpur,Cloud AI,4400.0
4,4,Praveen kumar,22,36000,Pune,HR,7200.0
5,5,Siddhant sharma,22,40000,Channi,Coliud AI,8000.0
6,6,Pankaj Meena,25,50000,Channi,BDE,10000.0

In [ ]:
# Update value - using columns name 
df.loc[df.Name == "Pankaj Meena", "Monthly_Salary"] = 45000
df

,Unnamed: 0,Name,Age,Monthly_Salary,City,Team,Bonus
0,0,Pushpkar Roy,22,56000,Jabalpur,Data Analyst,11200.0
1,1,Ankit Roy,26,45000,Pune,HR,9000.0
2,2,Anurag Pal,21,51000,Delhi,BDE,10200.0
3,3,Piyush panday,23,22000,Jabalpur,Cloud AI,4400.0
4,4,Praveen kumar,22,36000,Pune,HR,7200.0
5,5,Siddhant sharma,22,40000,Channi,Coliud AI,8000.0
6,6,Pankaj Meena,25,45000,Channi,BDE,10000.0

## Delete value - Row and column value

In [ ]:
# Drop Rows 

df.drop(df[df.Name == "Pankaj Meena"].index)   # Drop Rows Axis = 0, mean Drop Rows

,Unnamed: 0,Name,Age,Monthly_Salary,City,Team,Bonus
0,0,Pushpkar Roy,22,56000,Jabalpur,Data Analyst,11200.0
1,1,Ankit Roy,26,45000,Pune,HR,9000.0
2,2,Anurag Pal,21,51000,Delhi,BDE,10200.0
3,3,Piyush panday,23,22000,Jabalpur,Cloud AI,4400.0
4,4,Praveen kumar,22,36000,Pune,HR,7200.0
5,5,Siddhant sharma,22,40000,Channi,Coliud AI,8000.0

In [ ]:
# Drop Rows with the bases of Index number 

df.drop(1,axis=0)   # Index name

,Unnamed: 0,Name,Age,Monthly_Salary,City,Team,Bonus
0,0,Pushpkar Roy,22,56000,Jabalpur,Data Analyst,11200.0
2,2,Anurag Pal,21,51000,Delhi,BDE,10200.0
3,3,Piyush panday,23,22000,Jabalpur,Cloud AI,4400.0
4,4,Praveen kumar,22,36000,Pune,HR,7200.0
5,5,Siddhant sharma,22,40000,Channi,Coliud AI,8000.0
6,6,Pankaj Meena,25,45000,Channi,BDE,10000.0

## Drop columns

__Internal Concept of drop()__

Drop does not physically remove data immediately.

It:

    Creates new object (unless inplace)
    Rebuilds index
    Returns new DataFrame

That’s why large drops are expensive.

In [ ]:
df.drop("Unnamed: 0", axis= 1, inplace= True)

In [ ]:
df

,Name,Age,Monthly_Salary,City,Team,Bonus,Salary
0,Pushpkar Roy,22,56000.0,Jabalpur,Data Analyst,11200.0,NaN
1,Ankit Roy,26,45000.0,Pune,HR,9000.0,NaN
2,Anurag Pal,21,51000.0,Delhi,BDE,10200.0,NaN
3,Piyush panday,23,22000.0,Jabalpur,Cloud AI,4400.0,NaN
4,Praveen kumar,22,36000.0,Pune,HR,7200.0,NaN
5,Siddhant sharma,22,40000.0,Channi,Coliud AI,8000.0,NaN
6,Pushpkar Roy,22,NaN,Jabalpur,NaN,NaN,56000.0
7,Ankit Roy,26,NaN,Pune,NaN,NaN,45000.0
8,Anurag Pal,21,NaN,Delhi,NaN,NaN,51000.0
9,Piyush panday,23,NaN,Jabalpur,NaN,NaN,22000.0
10,Praveen kumar,22,NaN,Pune,NaN,NaN,36000.0
11,Siddhant sharma,22,NaN,Channi,NaN,NaN,40000.0

In [ ]:

df = df.drop(df[df.Name == "Pankaj Meena"].index)

In [ ]:
df

              Name  Age  Monthly_Salary      City          Team    Bonus
0     Pushpkar Roy   22           56000  Jabalpur  Data Analyst  11200.0
1        Ankit Roy   26           45000      Pune            HR   9000.0
2       Anurag Pal   21           51000     Delhi           BDE  10200.0
3    Piyush panday   23           22000  Jabalpur      Cloud AI   4400.0
4    Praveen kumar   22           36000      Pune            HR   7200.0
5  Siddhant sharma   22           40000    Channi     Coliud AI   8000.0

We have 2 way to save deleted Column save in system 
1. Using inplalce = True (Example = df = df.drop(df[df.Name == "Pankaj Meena"].index))
2. df = code             (Example = df.drop("Unnamed: 0", axis= 1, inplace= True))

## How to delete multiple Columns

In [ ]:
df.drop(["Bonus", "Team"], axis= 1)   # Delete multiple columns

              Name  Age  Monthly_Salary      City
0     Pushpkar Roy   22           56000  Jabalpur
1        Ankit Roy   26           45000      Pune
2       Anurag Pal   21           51000     Delhi
3    Piyush panday   23           22000  Jabalpur
4    Praveen kumar   22           36000      Pune
5  Siddhant sharma   22           40000    Channi

## Sort Values

🧠 Important Sorting Concepts

    Sorting returns new DataFrame
    NaN values go to bottom by default
    Can control using:

df.sort_values("Salary", na_position="first")

In [ ]:
df.sort_values("Monthly_Salary")                   # Ascending Order 
df.sort_values("Monthly_Salary", ascending= False) # Descending Order

              Name  Age  Monthly_Salary      City          Team    Bonus
0     Pushpkar Roy   22           56000  Jabalpur  Data Analyst  11200.0
2       Anurag Pal   21           51000     Delhi           BDE  10200.0
1        Ankit Roy   26           45000      Pune            HR   9000.0
5  Siddhant sharma   22           40000    Channi     Coliud AI   8000.0
4    Praveen kumar   22           36000      Pune            HR   7200.0
3    Piyush panday   23           22000  Jabalpur      Cloud AI   4400.0

<h2 style="color:darkorange; font-weight:bold;">Working with date Value</h2>

In [43]:
df["DOJ"] = ["2025-01-21","2025-07-01","2025-03-03","2025-11-06","2025-05-05","2025-09-15",]

In [44]:
df

,Unnamed: 0,Name,Age,Monthly_Salary,City,Team,DOJ
0,0,Pushpkar Roy,22,56000,Jabalpur,Data Analyst,2025-01-21
1,1,Ankit Roy,26,45000,Pune,HR,2025-07-01
2,2,Anurag Pal,21,51000,Delhi,BDE,2025-03-03
3,3,Piyush panday,23,22000,Jabalpur,Cloud AI,2025-11-06
4,4,Praveen kumar,22,36000,Pune,HR,2025-05-05
5,5,Siddhant sharma,22,40000,Channi,Coliud AI,2025-09-15

In [ ]:
df.dtypes            # They conceder DOJ as a object

Name       object
Age         int64
City       object
Team       object
Bonus     float64
Salary      int64
DOJ        object
dtype: object

## How to update Date column object to date

In [ ]:
df["DOJ"] = pd.to_datetime(df["DOJ"])

In [ ]:
df.dtypes

Name              object
Age                int64
City              object
Team              object
Bonus            float64
Salary             int64
DOJ       datetime64[ns]
dtype: object

In [ ]:
df1 = df

In [42]:
df

   Unnamed: 0             Name  Age  Monthly_Salary      City          Team
0           0     Pushpkar Roy   22           56000  Jabalpur  Data Analyst
1           1        Ankit Roy   26           45000      Pune            HR
2           2       Anurag Pal   21           51000     Delhi           BDE
3           3    Piyush panday   23           22000  Jabalpur      Cloud AI
4           4    Praveen kumar   22           36000      Pune            HR
5           5  Siddhant sharma   22           40000    Channi     Coliud AI

In [ ]:
# Drop DOB column 
df1 = df1.drop("DOB", axis= 1)

## How to replace

## How to extract Year from the date columns

__dt mean Datetime in short__

In [ ]:
df

               Name  Age      City          Team   Bonus  Salary        DOJ
6      Pushpkar Roy   22  Jabalpur  Data Analyst  5600.0   56000 2025-01-21
7         Ankit Roy   26      Pune            HR  4500.0   45000 2025-07-01
8        Anurag Pal   21     Delhi           BDE  5100.0   51000 2025-03-03
9     Piyush panday   23  Jabalpur      Cloud AI  2200.0   22000 2025-11-06
10    Praveen kumar   22      Pune            HR  3600.0   36000 2025-05-05
11  Siddhant sharma   22    Channi     Coliud AI  4000.0   40000 2025-09-15

In [45]:
df.dtypes

Unnamed: 0         int64
Name              object
Age                int64
Monthly_Salary     int64
City              object
Team              object
DOJ               object
dtype: object

In [46]:
df["DOJ"] = pd.to_datetime(df["DOJ"])

In [47]:
# Extract from single use 
df["DOJ"].dt.year   #dt mean Datetime

0    2025
1    2025
2    2025
3    2025
4    2025
5    2025
Name: DOJ, dtype: int32

In [48]:
# Extract from the table 
df["Year"] = df["DOJ"].dt.year    #dt mean Datetime

In [49]:
df

,Unnamed: 0,Name,Age,Monthly_Salary,City,Team,DOJ,Year
0,0,Pushpkar Roy,22,56000,Jabalpur,Data Analyst,2025-01-21,2025
1,1,Ankit Roy,26,45000,Pune,HR,2025-07-01,2025
2,2,Anurag Pal,21,51000,Delhi,BDE,2025-03-03,2025
3,3,Piyush panday,23,22000,Jabalpur,Cloud AI,2025-11-06,2025
4,4,Praveen kumar,22,36000,Pune,HR,2025-05-05,2025
5,5,Siddhant sharma,22,40000,Channi,Coliud AI,2025-09-15,2025

## Extract Month and Month name from the column

In [50]:
df["DOJ"].dt.month    # They give Month number                             #dt mean Datetime 
df["DOJ"].dt.month_name() #They give month name, Using () in month name     #dt mean Datetime

0      January
1         July
2        March
3     November
4          May
5    September
Name: DOJ, dtype: object

In [51]:
df["Mont_Name"] = df["DOJ"].dt.month_name()           #dt mean Datetime 
df

,Unnamed: 0,Name,Age,Monthly_Salary,City,Team,DOJ,Year,Mont_Name
0,0,Pushpkar Roy,22,56000,Jabalpur,Data Analyst,2025-01-21,2025,January
1,1,Ankit Roy,26,45000,Pune,HR,2025-07-01,2025,July
2,2,Anurag Pal,21,51000,Delhi,BDE,2025-03-03,2025,March
3,3,Piyush panday,23,22000,Jabalpur,Cloud AI,2025-11-06,2025,November
4,4,Praveen kumar,22,36000,Pune,HR,2025-05-05,2025,May
5,5,Siddhant sharma,22,40000,Channi,Coliud AI,2025-09-15,2025,September

## Extract Day and and Day name

In [52]:
df["DOJ"].dt.day               #Extract date number from the column 
df["DOJ"].dt.day_name()        # Extract day name from the column , using () in the end of the code 
                               # df mean datetime

0     Tuesday
1     Tuesday
2      Monday
3    Thursday
4      Monday
5      Monday
Name: DOJ, dtype: object

In [53]:
df["Day_name"] = df["DOJ"].dt.day_name()     #Extract Day name in the table 
df

,Unnamed: 0,Name,Age,Monthly_Salary,City,Team,DOJ,Year,Mont_Name,Day_name
0,0,Pushpkar Roy,22,56000,Jabalpur,Data Analyst,2025-01-21,2025,January,Tuesday
1,1,Ankit Roy,26,45000,Pune,HR,2025-07-01,2025,July,Tuesday
2,2,Anurag Pal,21,51000,Delhi,BDE,2025-03-03,2025,March,Monday
3,3,Piyush panday,23,22000,Jabalpur,Cloud AI,2025-11-06,2025,November,Thursday
4,4,Praveen kumar,22,36000,Pune,HR,2025-05-05,2025,May,Monday
5,5,Siddhant sharma,22,40000,Channi,Coliud AI,2025-09-15,2025,September,Monday

## How to join Additional date in DOJ and datetime column

In [54]:
df["Day_name"]

0     Tuesday
1     Tuesday
2      Monday
3    Thursday
4      Monday
5      Monday
Name: Day_name, dtype: object

In [56]:
# 🟢 Map Function (For Single Column)
df["City_Code"] = df["City"].map({
    "Delhi": 1,
    "Jabalpur":2,
    "Pune":3,
    "Channi":4
})
df

,Unnamed: 0,Name,Age,Monthly_Salary,City,Team,DOJ,Year,Mont_Name,Day_name,City_Code
0,0,Pushpkar Roy,22,56000,Jabalpur,Data Analyst,2025-01-21,2025,January,Tuesday,2
1,1,Ankit Roy,26,45000,Pune,HR,2025-07-01,2025,July,Tuesday,3
2,2,Anurag Pal,21,51000,Delhi,BDE,2025-03-03,2025,March,Monday,1
3,3,Piyush panday,23,22000,Jabalpur,Cloud AI,2025-11-06,2025,November,Thursday,2
4,4,Praveen kumar,22,36000,Pune,HR,2025-05-05,2025,May,Monday,3
5,5,Siddhant sharma,22,40000,Channi,Coliud AI,2025-09-15,2025,September,Monday,4

In [57]:
df

,Unnamed: 0,Name,Age,Monthly_Salary,City,Team,DOJ,Year,Mont_Name,Day_name,City_Code
0,0,Pushpkar Roy,22,56000,Jabalpur,Data Analyst,2025-01-21,2025,January,Tuesday,2
1,1,Ankit Roy,26,45000,Pune,HR,2025-07-01,2025,July,Tuesday,3
2,2,Anurag Pal,21,51000,Delhi,BDE,2025-03-03,2025,March,Monday,1
3,3,Piyush panday,23,22000,Jabalpur,Cloud AI,2025-11-06,2025,November,Thursday,2
4,4,Praveen kumar,22,36000,Pune,HR,2025-05-05,2025,May,Monday,3
5,5,Siddhant sharma,22,40000,Channi,Coliud AI,2025-09-15,2025,September,Monday,4

## How to add addional date in date columns

In [58]:
df["DOJ"] + pd.Timedelta(days= 90)

0   2025-04-21
1   2025-09-29
2   2025-06-01
3   2026-02-04
4   2025-08-03
5   2025-12-14
Name: DOJ, dtype: datetime64[ns]

<h2 style="color:darkorange; font-weight:bold;">Handleing missing values</h2>

In [59]:
df

,Unnamed: 0,Name,Age,Monthly_Salary,City,Team,DOJ,Year,Mont_Name,Day_name,City_Code
0,0,Pushpkar Roy,22,56000,Jabalpur,Data Analyst,2025-01-21,2025,January,Tuesday,2
1,1,Ankit Roy,26,45000,Pune,HR,2025-07-01,2025,July,Tuesday,3
2,2,Anurag Pal,21,51000,Delhi,BDE,2025-03-03,2025,March,Monday,1
3,3,Piyush panday,23,22000,Jabalpur,Cloud AI,2025-11-06,2025,November,Thursday,2
4,4,Praveen kumar,22,36000,Pune,HR,2025-05-05,2025,May,Monday,3
5,5,Siddhant sharma,22,40000,Channi,Coliud AI,2025-09-15,2025,September,Monday,4

## How to check null values

In [60]:
df.isnull() # Check all null values

,Unnamed: 0,Name,Age,Monthly_Salary,City,Team,DOJ,Year,Mont_Name,Day_name,City_Code
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False

In [61]:
df.isnull().sum() # Show total how many null values we have

Unnamed: 0        0
Name              0
Age               0
Monthly_Salary    0
City              0
Team              0
DOJ               0
Year              0
Mont_Name         0
Day_name          0
City_Code         0
dtype: int64

In [62]:
import numpy as np

In [63]:
df.loc[df.Name  == "Praveen kumar", "Salary"] = np.nan

In [64]:
df.isnull()

,Unnamed: 0,Name,Age,Monthly_Salary,City,Team,DOJ,Year,Mont_Name,Day_name,City_Code,Salary
0,False,False,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,False,True
5,False,False,False,False,False,False,False,False,False,False,False,True

In [65]:
df.isnull().sum()

Unnamed: 0        0
Name              0
Age               0
Monthly_Salary    0
City              0
Team              0
DOJ               0
Year              0
Mont_Name         0
Day_name          0
City_Code         0
Salary            6
dtype: int64

In [66]:
df

,Unnamed: 0,Name,Age,Monthly_Salary,City,Team,DOJ,Year,Mont_Name,Day_name,City_Code,Salary
0,0,Pushpkar Roy,22,56000,Jabalpur,Data Analyst,2025-01-21,2025,January,Tuesday,2,NaN
1,1,Ankit Roy,26,45000,Pune,HR,2025-07-01,2025,July,Tuesday,3,NaN
2,2,Anurag Pal,21,51000,Delhi,BDE,2025-03-03,2025,March,Monday,1,NaN
3,3,Piyush panday,23,22000,Jabalpur,Cloud AI,2025-11-06,2025,November,Thursday,2,NaN
4,4,Praveen kumar,22,36000,Pune,HR,2025-05-05,2025,May,Monday,3,NaN
5,5,Siddhant sharma,22,40000,Channi,Coliud AI,2025-09-15,2025,September,Monday,4,NaN

## how to fill null values

In [67]:
df = df.fillna(45000)   # Using fillna for fill null values

In [68]:
df

,Unnamed: 0,Name,Age,Monthly_Salary,City,Team,DOJ,Year,Mont_Name,Day_name,City_Code,Salary
0,0,Pushpkar Roy,22,56000,Jabalpur,Data Analyst,2025-01-21,2025,January,Tuesday,2,45000.0
1,1,Ankit Roy,26,45000,Pune,HR,2025-07-01,2025,July,Tuesday,3,45000.0
2,2,Anurag Pal,21,51000,Delhi,BDE,2025-03-03,2025,March,Monday,1,45000.0
3,3,Piyush panday,23,22000,Jabalpur,Cloud AI,2025-11-06,2025,November,Thursday,2,45000.0
4,4,Praveen kumar,22,36000,Pune,HR,2025-05-05,2025,May,Monday,3,45000.0
5,5,Siddhant sharma,22,40000,Channi,Coliud AI,2025-09-15,2025,September,Monday,4,45000.0

<h2 style="color:darkorange; font-weight:bold;">Aggregation and Group by</h2>

__How to count a value__

In [69]:
df["Team"].value_counts()

Team
HR              2
Data Analyst    1
BDE             1
Cloud AI        1
Coliud AI       1
Name: count, dtype: int64

In [70]:
df[df["Team"]=="HR"].value_counts()  # Using like a filter

Unnamed: 0  Name           Age  Monthly_Salary  City  Team  DOJ         Year  Mont_Name  Day_name  City_Code  Salary
1           Ankit Roy      26   45000           Pune  HR    2025-07-01  2025  July       Tuesday   3          45000.0    1
4           Praveen kumar  22   36000           Pune  HR    2025-05-05  2025  May        Monday    3          45000.0    1
Name: count, dtype: int64

## how to use Group by

In [71]:
df

,Unnamed: 0,Name,Age,Monthly_Salary,City,Team,DOJ,Year,Mont_Name,Day_name,City_Code,Salary
0,0,Pushpkar Roy,22,56000,Jabalpur,Data Analyst,2025-01-21,2025,January,Tuesday,2,45000.0
1,1,Ankit Roy,26,45000,Pune,HR,2025-07-01,2025,July,Tuesday,3,45000.0
2,2,Anurag Pal,21,51000,Delhi,BDE,2025-03-03,2025,March,Monday,1,45000.0
3,3,Piyush panday,23,22000,Jabalpur,Cloud AI,2025-11-06,2025,November,Thursday,2,45000.0
4,4,Praveen kumar,22,36000,Pune,HR,2025-05-05,2025,May,Monday,3,45000.0
5,5,Siddhant sharma,22,40000,Channi,Coliud AI,2025-09-15,2025,September,Monday,4,45000.0

In [72]:
df.groupby("Team")["Monthly_Salary"].sum()   # Aggregation based on group by

Team
BDE             51000
Cloud AI        22000
Coliud AI       40000
Data Analyst    56000
HR              81000
Name: Monthly_Salary, dtype: int64

__How to use multiple group by funtion__

In [73]:
df.groupby("Team").agg({"Monthly_Salary": "mean", "Name": "count"})   # agg is represent aggregation

              Monthly_Salary  Name
Team
BDE                  51000.0     1
Cloud AI             22000.0     1
Coliud AI            40000.0     1
Data Analyst         56000.0     1
HR                   40500.0     2

<h2 style="color:darkorange; font-weight:bold;">Concatenate and merge Dataframe (JOINS)</h2>

In [74]:
df1 = pd.DataFrame({
    "ID":[1,2,3],
    "Name":["A","B","C"]
})

In [75]:
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [76]:
df2 = pd.DataFrame({
    "ID":[1,2,2,4],
    "Score":[88,96,77,79]
})

df2

   ID  Score
0   1     88
1   2     96
2   2     77
3   4     79

## How to concat 2 or or then 2 tables

In [ ]:
pd.concat([df1,df2], axis= 0)  # Vertical joint / row level join / top-on-top join

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   88.0
1   2  NaN   96.0
2   2  NaN   77.0
3   4  NaN   79.0

In [ ]:
pd.concat([df1,df2], axis= 1) #Horezontal joint / column joint / side on side joint

    ID Name  ID  Score
0  1.0    A   1     88
1  2.0    B   2     96
2  3.0    C   2     77
3  NaN  NaN   4     79

## How to merge or join the table

In [ ]:
pd.merge(df1,df2, how= "inner", on= "ID")   # Just like  a SQL first left table then right table 
                                            # Then how we join inner, outer, side, left, right, full 
                                            # then using ON mean in witch condetion or common column in both the table like SQL

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77

In [ ]:
# How to use left join
pd.merge(df1,df2, how= "left", on= "ID")

   ID Name  Score
0   1    A   88.0
1   2    B   96.0
2   2    B   77.0
3   3    C    NaN

In [85]:
# How to use right join 
pd.merge(df1,df2, how="right",on="ID")  # After typing how= python aotomaticaly show all type of join you use according to the work

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77
3   4  NaN     79

__What if the On column name is defferent in both the tables__

In [ ]:
pd.merge(df1,df2, how="inner", left_on= "ID", right_on= "ID")  # we are using left_on and right_on if the name of the column is different in both the table

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77