<h2 style="color:darkorange; font-weight:bold;">Python Real World Questions</h2>

In [1]:
import pandas as pd

In [2]:
data = {
    "Order_ID": [101,102,103,104,105,106,107,108,109,110],
    "Customer": ["Amit","Riya","Amit","Neha","Rohan","Riya","Neha","Amit","Rohan","Riya"],
    "Product": ["Laptop","Mouse","Keyboard","Laptop","Monitor","Keyboard","Mouse","Laptop","Mouse","Monitor"],
    "Category": ["Electronics","Accessories","Accessories","Electronics","Electronics","Accessories","Accessories","Electronics","Accessories","Electronics"],
    "Price": [60000,500,1500,62000,12000,1400,550,61000,600,12500],
    "Quantity": [1,2,1,1,1,3,2,1,5,1],
    "City": ["Delhi","Mumbai","Delhi","Pune","Mumbai","Delhi","Pune","Mumbai","Delhi","Pune"],
    "Rating": [4.5,4.0,3.8,4.7,4.2,3.9,4.1,4.8,3.7,4.3]
}

df = pd.DataFrame(data)
df

   Order_ID Customer   Product     Category  Price  Quantity    City  Rating
0       101     Amit    Laptop  Electronics  60000         1   Delhi     4.5
1       102     Riya     Mouse  Accessories    500         2  Mumbai     4.0
2       103     Amit  Keyboard  Accessories   1500         1   Delhi     3.8
3       104     Neha    Laptop  Electronics  62000         1    Pune     4.7
4       105    Rohan   Monitor  Electronics  12000         1  Mumbai     4.2
5       106     Riya  Keyboard  Accessories   1400         3   Delhi     3.9
6       107     Neha     Mouse  Accessories    550         2    Pune     4.1
7       108     Amit    Laptop  Electronics  61000         1  Mumbai     4.8
8       109    Rohan     Mouse  Accessories    600         5   Delhi     3.7
9       110     Riya   Monitor  Electronics  12500         1    Pune     4.3

## Dat Cleanng

In [4]:
df.head(5)

   Order_ID Customer   Product     Category  Price  Quantity    City  Rating
0       101     Amit    Laptop  Electronics  60000         1   Delhi     4.5
1       102     Riya     Mouse  Accessories    500         2  Mumbai     4.0
2       103     Amit  Keyboard  Accessories   1500         1   Delhi     3.8
3       104     Neha    Laptop  Electronics  62000         1    Pune     4.7
4       105    Rohan   Monitor  Electronics  12000         1  Mumbai     4.2

In [12]:
df.shape

(10, 8)

In [13]:
df.dtypes

Order_ID      int64
Customer     object
Product      object
Category     object
Price         int64
Quantity      int64
City         object
Rating      float64
dtype: object

In [14]:
df.isna().sum()

Order_ID    0
Customer    0
Product     0
Category    0
Price       0
Quantity    0
City        0
Rating      0
dtype: int64

__Q1. Show all orders where price is greater than 10,000.__

In [15]:
df[df["Price"]> 10000]

   Order_ID Customer  Product     Category  Price  Quantity    City  Rating
0       101     Amit   Laptop  Electronics  60000         1   Delhi     4.5
3       104     Neha   Laptop  Electronics  62000         1    Pune     4.7
4       105    Rohan  Monitor  Electronics  12000         1  Mumbai     4.2
7       108     Amit   Laptop  Electronics  61000         1  Mumbai     4.8
9       110     Riya  Monitor  Electronics  12500         1    Pune     4.3

__Q2. Find orders where:__

    City = Delhi
    Quantity greater than 2

In [ ]:
city = df[df["City"] == "Delhi"]
city[city["Quantity"] > 2]

   Order_ID Customer   Product     Category  Price  Quantity   City  Rating
5       106     Riya  Keyboard  Accessories   1400         3  Delhi     3.9
8       109    Rohan     Mouse  Accessories    600         5  Delhi     3.7

__Q3. Create a new column called:__

    Total_Amount

In [20]:
df["Total_Amount"] = df["Price"] * df["Quantity"]
df

,Order_ID,Customer,Product,Category,Price,Quantity,City,Rating,Total_Amount
0,101,Amit,Laptop,Electronics,60000,1,Delhi,4.5,60000
1,102,Riya,Mouse,Accessories,500,2,Mumbai,4.0,1000
2,103,Amit,Keyboard,Accessories,1500,1,Delhi,3.8,1500
3,104,Neha,Laptop,Electronics,62000,1,Pune,4.7,62000
4,105,Rohan,Monitor,Electronics,12000,1,Mumbai,4.2,12000
5,106,Riya,Keyboard,Accessories,1400,3,Delhi,3.9,4200
6,107,Neha,Mouse,Accessories,550,2,Pune,4.1,1100
7,108,Amit,Laptop,Electronics,61000,1,Mumbai,4.8,61000
8,109,Rohan,Mouse,Accessories,600,5,Delhi,3.7,3000
9,110,Riya,Monitor,Electronics,12500,1,Pune,4.3,12500

__Q4.  Sort the dataframe by:__

    Total_Amount (descending)
    Show top 5 rows.

In [28]:
df.sort_values(by="Total_Amount", ascending= False).head(5)

,Order_ID,Customer,Product,Category,Price,Quantity,City,Rating,Total_Amount
3,104,Neha,Laptop,Electronics,62000,1,Pune,4.7,62000
7,108,Amit,Laptop,Electronics,61000,1,Mumbai,4.8,61000
0,101,Amit,Laptop,Electronics,60000,1,Delhi,4.5,60000
9,110,Riya,Monitor,Electronics,12500,1,Pune,4.3,12500
4,105,Rohan,Monitor,Electronics,12000,1,Mumbai,4.2,12000

Q5. Find:

    Total unique customers
    Total unique products

In [32]:
# Total Unique customer 
customer = df["Customer"].unique()
customer

array(['Amit', 'Riya', 'Neha', 'Rohan'], dtype=object)

In [34]:
# Total unique product 
df["Product"].unique()

array(['Laptop', 'Mouse', 'Keyboard', 'Monitor'], dtype=object)

In [36]:
# Try to solce both togather 
df[["Customer", "Product"]].nunique()

Customer    4
Product     4
dtype: int64

__Q6. Find:__

    Total Sales by Product

In [37]:
df.groupby("Product")["Total_Amount"].sum()

Product
Keyboard      5700
Laptop      183000
Monitor      24500
Mouse         5100
Name: Total_Amount, dtype: int64

__Q7. Find:__

    Average Rating for each Category
    Sort result highest rating first

In [42]:
round(df.groupby("Product")["Rating"].mean().sort_values(ascending= False),2)

Product
Laptop      4.67
Monitor     4.25
Mouse       3.93
Keyboard    3.85
Name: Rating, dtype: float64

__Q8. Find the customer who spent the most money.__

    Output should show:
    Customer | Total Spending

In [43]:
df.groupby("Customer")["Total_Amount"].sum().sort_values(ascending=False).reset_index()

  Customer  Total_Amount
0     Amit        122500
1     Neha         63100
2     Riya         17700
3    Rohan         15000

__Q9. Find which city generated the highest revenue.__

In [44]:
df.groupby("City")["Total_Amount"].sum().sort_values(ascending= False).reset_index()

     City  Total_Amount
0    Pune         75600
1  Mumbai         74000
2   Delhi         68700

__Q10. Find:__

    Top 3 most sold products
    Based on total quantity sold.

In [46]:
df.groupby("Product")["Quantity"].sum().sort_values(ascending= False).reset_index().head(3)

    Product  Quantity
0     Mouse         9
1  Keyboard         4
2    Laptop         3